"""add index phone

Revision ID: 19dc8b0ae773
Revises: 3c86a2bcb416
Create Date: 2025-03-08 15:33:14.864861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dc8b0ae773'
down_revision = '3c86a2bcb416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_phone', 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone', table_name='user')
    # ### end Alembic commands ###
