"""phone unique

Revision ID: 3c86a2bcb416
Revises: 9362bc9ad285
Create Date: 2025-03-08 15:26:50.175995

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3c86a2bcb416"
down_revision = "9362bc9ad285"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
