"""add articles

Revision ID: 5584a9c1fedc
Revises: 38ba75909bfe
Create Date: 2024-08-04 15:46:16.794896

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from authenticity_product.models import TAG_CHOICES


# revision identifiers, used by Alembic.
revision = "5584a9c1fedc"
down_revision = "38ba75909bfe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tag", sqlalchemy_utils.types.choice.ChoiceType(TAG_CHOICES), nullable=False),
        sa.Column("owner_manufacturer_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_manufacturer_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("articles")
    # ### end Alembic commands ###
