apiVersion: v1
kind: ConfigMap
metadata:
  name: authenticity-product
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-6"
data:
  DB_HOST: {{ .Values.DB_HOST }}
  DB_NAME: {{ .Values.DB_NAME }}
  DB_USER: {{ .Values.DB_USER }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD }}
